version: "3.8"
services:
  angular_app:
    build: .
    container_name: angular_app
    expose:
      - "8080"

  caddy:
    image: caddy:latest
    container_name: caddy
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - angular_app

volumes:
  caddy_data:
  caddy_config:

