name: Angular CI/CD Deploy to Local Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Build & Deploy Angular App
        run: |
          docker compose down
          docker compose up --build -d

